### ISSUE TITLE
Error: stream.push() after EOF

### ISSUE THREAD

**Issue by karli2000** [SaltwaterC/http-request#17] opened 2013-06-14 06:59 UTC
Hi,

don't know if this is http-get only related or an issue with node 0.10.10:
i get from time to time when i fetch a lot of URLs this error:

``` javascript
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:146:15)
    at IncomingMessage.Readable.push (_stream_readable.js:127:10)
    at HTTPParser.parserOnBody [as onBody] (http.js:143:22)
    at Socket.socketOnData [as ondata] (http.js:1556:20)
    at TCP.onread (net.js:510:27)
```

any ideas how to fix this?
Thank you!

**Comment by SaltwaterC** [comment] 2013-06-14 14:03
Hi,

I didn't encounter this issue and I do download a lot of stuff with it. However, I'm still on node.js 0.8. Have various migration issues with 0.10 due to Stream v2. I think you found a node.js bug (as claimed by #[5439](https://github.com/joyent/node/issues/5439) which you already know about). I see that the error is into the stream library which was reimplemented in 0.10. Even the docs claim that Stream v2 is [unstable](http://nodejs.org/api/stream.html#stream_stream). I can say that I've seen this with HTTP v2 in node.js v0.6 - quite a minefield in edge cases.

For a proper bug fix, it needs to be reproduced in a reliable way. By its description, it looks like some sort of race condition. I'll look into it, but no ETA as these issues are non-trivial.

Regards.

**Comment by karli2000** [comment] 2013-06-14 15:03
Hi,

thank you for the fast answer & thank your for the effort!
Yes, it looks like some sort of race condition, i am using your great http-get for crawling up to 50 pages per second and then sometimes the error comes. 
Looks like i have to live with it until there is a nodejs update.

Thank you,
Max

**Comment by SaltwaterC** [comment] 2013-06-14 18:29
I was surprised to find out that node.js v0.8 still has some maintenance going on. It is on v0.8.25. You could give it a spin if you don't depend on v0.10.

**Comment by SaltwaterC** [comment] 2013-11-06 11:52
Released http-request. Keeping this open for the time being, but it would be helpful to know if the issue is still there.

Thanks,
Ștefan

**Comment by SaltwaterC** [comment] 2014-01-30 16:50
Since there aren't complains with the new lib, closing this one.

**Closed as completed by SaltwaterC** 2014-01-30 16:50 UTC
