### ISSUE TITLE
When reporting an error result.url is not set

### ISSUE THREAD

**Issue by karli2000** [SaltwaterC/http-request#15] opened 2013-01-09 07:53 UTC
Hi,

sorry, another issue :)

When using the HEAD-function of http-get and requesting an URL that returns a error (404, 403, 502, etc.) the result object is not set. For example try this URL:
http://t.co/w0ErWk1f 

This resovles to:
http://www.republicof3.com/5-ux-trends-of-2012-continuing-in-2013/

When making a HEAD-request for the t.co URL the resulting URL returns a 403 error, but it would be nice when the result object has at least the last URL that was called, otherwise you don't have a clue what URL was responsible for the error.

Thank you,
Max

**Comment by SaltwaterC** [comment] 2013-01-09 08:05
The result not being set in case of error is by design. Or should I say, discovery. I am keeping a clear convention of passing either the (error) or the (null, result) arguments to the callback. This way you don't have to exercise the muscle memory for remembering that stuff may be in result if error is set. It used to be the other way around when I started http-get, but things got complicated and I refactored those bits.

``` javascript
// the logic doesn't get any easier than this
if (error) {
  // handle error
} else {
  // handle result
}
```

I'll attach an url property to the error argument if it is set.

**Comment by karli2000** [comment] 2013-01-09 08:07
Perfect, i can understand the design decision, it completly makes sense to attach the url property to the error argument, this would fix my problem perfectly.

**Comment by SaltwaterC** [comment] 2013-01-09 08:14
``` bash
$ node
> var http = require('./')
> http.head('http://t.co/w0ErWk1f', function (err, res) {console.log(err, res)})
> { [Error: HTTP Error: 403]
  code: 403,
  headers: 
   { date: 'Wed, 09 Jan 2013 08:11:40 GMT',
     server: 'LiteSpeed',
     connection: 'Keep-Alive',
     'keep-alive': 'timeout=5, max=100' },
  url: 'http://www.republicof3.com/5-ux-trends-of-2012-continuing-in-2013/' } undefined
```

Seems just about right. I need to check what tests can cover it as there are a lot of exit points due to errors. Implemented it for both GET and HEAD.

**Comment by karli2000** [comment] 2013-01-09 08:28
Perfect, that is exactly what i need!

**Comment by SaltwaterC** [comment] 2013-01-09 09:03
Release tagged and published to npm. Broke the commit message, therefore have to close this ticket by hand. Please let me know if you encounter any issues with the new functionality.

**Closed as completed by SaltwaterC** 2013-01-09 09:03 UTC

**Comment by karli2000** [comment] 2013-01-09 09:16
Works perfect, thank you very much!

Max
